# change change change change
name: automerge
# Controls when the workflow will run
on:
  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2        
      - name: AutoMerge
        uses: raulnq/git-flow-automerge@v0.3.0
        with:
          ### GITHUB_TOKEN.(required)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          ### branch type name. default: release (optional).
          release_branch_type: 'release'

          ### develop branch name. default: develop (optional).
          develop_branch: 'develop'
