name: automerge
on:
  push:
    branches:
      - 'release/**'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
      - name: AutoMerge
        uses: raulnq/git-flow-automerge@v0.4.1
        with:
          github_token: ${{ secrets.AUTOMERGE_TOKEN }}
          release_branch_type: 'release'
          develop_branch: 'develop'