# change change
name: CI
# Controls when the workflow will run
on:
  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: yanamura/git-flow-merge-action@v1
        with: 
          ### GITHUB_TOKEN.(required)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          ### branch name which merged to develop and master branch.(required)
          ### ex. release/1.1.0, hotfix_branch
          branch: ${{ steps.extract_branch.outputs.branch }}

          ### develop branch name. default: develop (optional).
          develop_branch: 'release/2.0.0'

          ### main branch name. default: master (optional).
          main_branch: 'main'